# vim: set ts=2 sw=2 sts=2 et:
#
# Module fixtures
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

XLite\Model\Config:
  - name: write_key
    category: XC\Concierge
    value: 'FGzphKUhESFKsjwsdFVKjpB4V6NYZscy'
  - name: company_id
    category: XC\Concierge
    value: ''
  - name: user_id
    category: XC\Concierge
    value: 'user1'
  - name: additional_config_loaded
    category: XC\Concierge
    value: ''
